### ISSUE TITLE
BetterPrinting.createF(): create file if passed path does not exist

### ISSUE THREAD

**Issue by NickolaiBeloguzov** [Butter-mit-Brot/BetterPrinting#3]
Hello, me again!

So I've looked through your codebase once again and I've a proposal:
If file passed in createF() function does not exist, function can create it.

Right now you open file in 'w' mode. This mode assumes that file already exists and if it does not, the script will raise an exception.

I've already modified this function so if it doesn't find passed file, it will just create one, write everything down and close it.

I can make a PR to merge along with some other improvements in just a sec. I just want to know if you want this kind of functionality implemented in your library.

_Side note: I've also updated your setup.py file. Now Long description is generated by a dedicated function. If you do not want this kind of thing, tell me and I delete it. You can see all changes in my PR_

**Comment by NickolaiBeloguzov** [comment]
Update: I've create a Pull request that resolves issues #1, #2 and #3

**Comment by Butter-mit-Brot** [comment]
Thank you I saw your Pull request.

I know that 'w' will overwrite the text and 'a' appends the text in an existing file but I did not really want to make an complicated writing mode I just wanted to easy create files with content :) I know for people that are more intermediate its easy to understand why it overwrites but for beginners not, so basically you are completely right and I just did not think about that :)

For the changes in my setup.py I don't really know why I should change this but I was not really sure about that file either... I research things about making packages and found this I was curios and a little bit lazy so I copied it hahaha 

But overall thank you for your great work  for my little shit library that was considered as a fun project for me  to explore a little bit of pythons packages...I think I will take this project and will work more on it like a real project :) 
I program in python since I was 12 years old and I always used other packages and I think I want to make them too... to help the growing community. 

I really want to thank you for your great support and sacrificing your time for me :)
